name: 'Montara CI'
description: 'Never merge a broken pipeline again'
author: 'Montara'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  webhookUrl:
    description: 'The URL of the webhook'
    required: true
  isStaging:
    description: 'Whether the test run is for staging or not'
    required: false

# Define your outputs here.
outputs:
  isPassing:
    description: 'Whether the test run passed or not'

runs:
  using: node20
  main: dist/index.js
