name: 'Montara CI'
description: 'Never merge a broken pipeline again'
author: 'Montara'

branding:
  icon: 'git-pull-request'
  color: 'white'

inputs:
  webhookUrl:
    description: 'The URL of the webhook'
    required: true
  isStaging:
    description: 'Whether the test run is for staging or not'
    required: false
  numRetries:
    description: 'The number of retries to attempt'
    required: false
    default: '60'

outputs:
  isPassing:
    description: 'Whether the test run passed or not'

runs:
  using: node20
  main: dist/index.js
